### ISSUE TITLE
Investigate problems involving WAI-ARIA Accordion behavior

### ISSUE THREAD

**Issue by bsunderhus** [microsoft/tabster#111]
Seems like we're having problems trying to reproduce the [WAI-ARIA Accordion spec](https://www.w3.org/TR/wai-aria-practices/#accordion) behavior with Grouper and Mover combined.

## Nice to haves for testing purposes

1. Reproduction of Accordion widget behavior in a storybook
2. Actual tests to ensure that we can respect the behavior.

**Comment by ling1726** [comment]
The issue with accordion is that is goes against the 'standard' arrow key behaviour which is to focus the next element in DOM order. In the case of the Accordion, the **completely optional** keyboard navigation pattern actually skips elements in DOM order.

**Comment by bsunderhus** [comment]
Should we close this issue with the merging of https://github.com/microsoft/fluentui/pull/21729 ? @ling1726  @mshoho
