### ISSUE TITLE
Groupper spelling?

### ISSUE THREAD

**Issue by micahgodbolt** [microsoft/tabster#151]
Is there a reason that Groupper is spelled with 2 p's? Group, Grouping, Grouper appear to be the proper spelling here. Is it a play on words? The spelling has made it all the way into our docs as well 

https://react.fluentui.dev/?path=/docs/components-menu--default#groupping-items

Would like to know if this is somehow intentional, and if it was a misspelling, if it'd be possible to fix it in tabster.

**Comment by mshoho** [comment]
Well, it was an attempt to use English of a non-native speaker. Like when you have run, you have runner — I thought when you have group, you also have groupper. Eventually I've discovered that it should have been one p, and the double p is a fish. So, it's the fishy part of our legacy :). And it won't be trivial to change it given the current consumption scenarios.

**Comment by micahgodbolt** [comment]
That totally makes sense. I think converting to standard spelling would be best for any external facing code/docs. The fish reference wouldn't be very obvious to an average user, so they would just see it as a misspelling.

**Comment by ling1726** [comment]
Actually `Groupper` avoids the fish thing 😄 

https://en.wikipedia.org/wiki/Grouper

**Comment by mbest** [comment]
"Groupper" looks very strange to me. Perhaps, just use "Group"
