### ISSUE TITLE
Ctrl + Tab is managed as Tab when Tabster App is in a Native Host

### ISSUE THREAD

**Issue by BryanValverdeU** [microsoft/tabster#179]
When using Ctrl + Tab inside of an Element that is part of the Tabster Context and the app is in a Native Host, Ctrl + Tab is executed as Tab.

Expected Result.
Ctrl + Tab should not be handled by Tabster.

**Comment by BryanValverdeU** [comment]
#180

**Comment by ling1726** [comment]
released under 2.1.2 https://www.npmjs.com/package/tabster/v/2.1.2
