### ISSUE TITLE
Unable to use mover with two divs next to each other?

### ISSUE THREAD

**Issue by tummalasujith** [microsoft/tabster#216]
Hi. We have two navigation groups and each sets tabster attributes. but when tabbing focus gets to first group and ignores next. When using shift tab, tab get to last element in second tab group and ignores first tab group. How can we use tabster with two tab groups next to each other?

Example here https://codesandbox.io/s/determined-chebyshev-p8v3do?file=/example.tsx

**Comment by micahgodbolt** [comment]
Reduced test case for this issue

https://codesandbox.io/s/awesome-antonelli-qo2dec

**Comment by micahgodbolt** [comment]
Also note that this used to work in tabster 2.x. Once react-components upgraded to 3.0.4 it stopped working.

**Comment by rdossantos2531** [comment]
Hey, found a workaround for this scenario. It was just a matter of setting memorizeCurrent to 'false': https://codesandbox.io/s/sparkling-rain-v7nv5b?file=/example.tsx 

Sharing in case this helps in any investigations.

cc @ling1726

**Comment by tummalasujith** [comment]
We will need memorizeCurrent for accessibility reasons. At least we know where the bug is.

**Comment by rdossantos2531** [comment]
> Hey, found a workaround for this scenario. It was just a matter of setting memorizeCurrent to 'false': [https://codesandbox.io/s/sparkling-rain-v7nv5b?file=/example.tsx ](https://codesandbox.io/s/sparkling-rain-v7nv5b?file=/example.tsx%C2%A0)
> 
> Sharing in case this helps in any investigations.
> 
> cc @ling1726

cc @ling1726 Hey! I just checked that v3.0.8 fixed the scenario where the two groups of buttons are direct siblings. But when they are not, as in the example above, we are still not able to tab between them (as we could in version 2.1.2). 

In the example on that link, you can try changing between fluent v9.10.1 (which uses tabster 3.0.8) and fluent v9.0.1 (which uses 2.1.2), and see the difference in behaviour. Any estimates of when a fix for this would be released?

**Comment by ling1726** [comment]
@rdossantos2531 thanks for reporting an the repro, we'll look into this

**Comment by ling1726** [comment]
Here's a repro using 3.0.8 https://codesandbox.io/s/ancient-microservice-x2ob3g

**Comment by ling1726** [comment]
Closed with #217
