### ISSUE TITLE
Error: 'using disposed tabster'.

### ISSUE THREAD

**Issue by vishalputta** [microsoft/tabster#238]
We are using tabster version - 4.1.1

We are seeing many 'using disposed tabster' errors in our product logs.
Callstack - 
![image](https://user-images.githubusercontent.com/8668295/219534777-46a359de-63a7-4ec0-ad13-58b236ec91f1.png)

I looked at the code and this could be causing issue.
https://github.com/microsoft/tabster/blame/c1b46b478fd0d75fe95b5653d525658e2bf16d6a/src/Modalizer.ts#:~:text=this._hiddenUpdateTimer%20%3D,%2C%20250)%3B

There is a possibility that this code could be executed after tabster is disposed, which would cause this error.

        this._hiddenUpdateTimer = this._win().setTimeout(() => {
            delete this._hiddenUpdateTimer;
            this._hiddenUpdate();
        }, 250);

@mshoho

**Comment by KagamiChan** [comment]
We got some such errors in jest testing environment with react testing framework after upgrading to latest Fluent UI v9, tests become flaky

@mshoho please let me know if there's something I can help, really want to get this issue resolved

**Comment by mshoho** [comment]
The fix for that is already in master. I can release canary for you to test right now. I wanted need to fix one more bug before releasing new version. Hopefully it'll be ready by the end of today (or first part of tomorrow).
