### ISSUE TITLE
Tabster async autoroot initialization breaks certain Fluent scenarios

### ISSUE THREAD

**Issue by bsunderhus** [microsoft/tabster#250]
This happened during the Modalizer revamp: [Modalizer revamp by mshoho · Pull Request #218 · microsoft/tabster (github.com)](https://github.com/microsoft/tabster/pull/218)

 

Reported issue: [[Bug]: dialog directly mounted with open=true could not get focus · Issue #26824 · microsoft/fluentui (github.com)](https://github.com/microsoft/fluentui/issues/26824)

Repro (also in the bug): [Sandbox - CodeSandbox (csb.app)](https://ml3ty9.csb.app/)

 

What seems to be happening is that since tabster@4.1.1 is that the autoroot creation is now async. This means that when a Fluent component that uses tabster is mounted, it generates errors because only the first usage of tabster initialized the autoroot. Since this is async, the React component can't actually use tabster on first render.

 

In the repro:

* The dialog is mounted
* tabster does not exist
* dialog initializes tabster
* dialog uses modalizer
* tabster error -> no autoroot created
* tabster creates autoroot
* modalizer is inactive because there was not root
* can't tab any element in the dialog
* use the console to call .focus() on an element
* now the modalizer is active

**Comment by angelo-mollame** [comment]
@bsunderhus can you please share where/how this issue was fixed? I can still repro the issue with "@fluentui/react-components": "9.49.1".

**Comment by bsunderhus** [comment]
We've updated latest tabster versions in Fluent v9 and the newest version should have this problem solved. Can you share a reproduction of the problem with "@fluentui/react-components": "9.49.1". @angelo-mollame ?

**Comment by angelo-mollame** [comment]
I created an issue and added repro steps here: https://github.com/microsoft/fluentui/issues/31421
